services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.kevvy.my.id
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.kevvy.my.id/
      - GENERIC_TIMEZONE=Asia/Jakarta
    volumes:
      - n8n_data:/home/node/.n8n

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: always
    network_mode: "host"
    command: tunnel run --token eyJhIjoiOTE4NGExNTI5NGFkZmY5NzJjY2U1OWMxZTNlMGE4ZDMiLCJ0IjoiNDJkODc2YjktZTk3MC00NmM1LWJjNGEtY2NjYWJjNTM4OWE5IiwicyI6Ik5XRmtPR0U1Tm1RdE5tUmxaUzAwWldRMUxUZ3daV010TTJSaU5qRm1NV001TlRreCJ9

volumes:
  n8n_data:
    